fu! s:load(module)
  exec 'source ' fnameescape(expand('~/.vim/modules/' . a:module . '.vim'))
endfu

call s:load('bundles')


if has('nvim')
  call s:load('ncompletion')
else
  call s:load('completion')
endif

call s:load('options')

call s:load('autocmds')
call s:load('statusline')
call s:load('unite')

call s:load('helpers')
call s:load('plugins')
call s:load('mappings')

call s:load('misc')

call s:load('colors')


augroup load_plugins_on_insert
  au!
  au InsertEnter * call plug#load('ultisnips', 'vim-smartinput')
        \| call s:load('smartinput')
        \| au! load_plugins_on_insert
augroup END

if filereadable(expand(".vimrc.local"))
  source .vimrc.local
endif

luafile ~/.vim/modules/init.lua

" ======== Tips:
" :au TextChangedI #(Run after typing) Debugging what plugins were run during text typing.
" :verbose vmap , # Show mapping for
" vim -u test_vimrc # Run vim with test_vimrc as source file
