# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
# Themes
ZSH_THEME="powerlevel10k/powerlevel10k"
# source ~/.zsh/themes/powerlevel9k.bash

ZSH_DOTENV_FILE=.export.env
plugins=(
  dotenv
  rails
  bundler
  colored-man-pages
  docker-compose
)

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Aliases
source ~/.zsh/aliases.zsh
source ~/.zsh/kuberaliases.zsh

# HYPHEN_INSENSITIVE="true"

# stty -ixon

export EDITOR=nvim
export LANG=en_US.utf-8

# More setoptions -> https://linux.die.net/man/1/zshoptions
setopt auto_list
setopt hist_ignore_all_dups
setopt share_history
setopt auto_menu
setopt share_history
setopt hist_reduce_blanks
export HOMEBREW_AUTO_UPDATE_SECS=604800
export HISTSIZE=200000
export SAVEHIST=200000
export HISTFILE="$HOME/.zsh_history"
export SAVEHIST=$HISTSIZE

zstyle ':completion:*' rehash true

# curl
export PATH="/usr/local/opt/curl/bin:$PATH"

eval "$(rbenv init -)"
eval "$(nodenv init -)"

# export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

# Python
# export PYTHONSTARTUP="$(ipython3 -m jedi repl)"
# export PIPENV_SYSTEM=1

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# ruby
export SOLARGRAPH_GLOBAL_CONFIG="$HOME/.config/solargraph/config.yml"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

#TMP
  export LDFLAGS="-L/usr/local/opt/postgresql@15/lib"
  export CPPFLAGS="-I/usr/local/opt/postgresql@15/include"
  export PATH=/usr/local/opt/postgresql@15/bin:$PATH

  export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
