# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export EDITOR=nvim


# Themes
# ZSH_THEME="awesomepanda"
source ~/.zsh/themes/powerlevel9k.bash

HYPHEN_INSENSITIVE="true"
source $ZSH/oh-my-zsh.sh

stty -ixon

plugins=(
  sudo
  globalias
  gem
  git
  osx
  dotenv
  ruby
  bundler
  rake
  rails
  command-not-found
)

# export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/mario/.rvm/bin:/home/mario/.rvm/bin"


export LANG=en_US.utf-8

export HOMEBREW_AUTO_UPDATE_SECS=86400
export HISTSIZE=200000
export SAVEHIST=200000
export HISTFILE="$HOME/.zsh_history"
export SAVEHIST=$HISTSIZE
setopt hist_ignore_all_dups

# al as tmux=«TERM=screen-256color tmux»
# al as tmux='tmux attach || tmux new' #save sessions
tmux_session=common

zstyle ':completion:*' rehash true

if which rbenv &> /dev/null
then
  # export PATH="$HOME/.rbenv/bin:$PATH"
  # export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"
  eval "$(rbenv init -)"
fi

# export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

### Added by the Heroku Toolbelt
# export PATH="/usr/local/heroku/bin:$PATH"
# GO
export GOPATH=$HOME/go

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export PATH=${PATH}:/usr/local/mysql/bin
export PATH="$(brew --prefix qt@5.5)/bin:$PATH"
export PATH="/usr/local/bin:/usr/local/sbin:$PATH"

# Custom dependencies exports
export LDFLAGS="-L/usr/local/opt/qt@5.5/lib"
export CPPFLAGS="-I/usr/local/opt/qt@5.5/include"
export PKG_CONFIG_PATH="/usr/local/opt/qt@5.5/lib/pkgconfig"

# export LDFLAGS="-L/usr/local/opt/postgresql@11/lib"
# export CPPFLAGS="-I/usr/local/opt/postgresql@11/include"
# export PKG_CONFIG_PATH="/usr/local/opt/postgresql@11/lib/pkgconfig"

PKG_CONFIG_PATH=/usr/local/opt/imagemagick@6/lib/pkgconfig
# Aliases
source ~/.zsh/aliases.zsh
